### PR TITLE
Parallel infra

### PR DESCRIPTION
**Pull request by MasoudAsadzade**
This pull request consists of:

Refactor CoreSMTSolver to extract Splitter functionality
Add separate MainSplitter class to the Api
***
Compare Parallel-infra to the Master Branch:
**QF_UF**
non-incremental-QF_UF-parallel-infra-2021-04-25_vs_master-2021-04-12

**QF_LRA**
non-incremental-QF_LRA-parallel-infra-2021-04-25_vs_master-2021-04-13

**QF_LIA**
non-incremental-QF_LIA-parallel-infra-2021-04-25_vs_master-2021-04-13

### CODE REVIEW

**Comment by aehyvari** [comment]
I'll convert this to a draft for now, I would like to work a little more on refactoring the search loops and hopefully increase the code reuse.

**Comment by aehyvari** [comment]
Btw the timeouts in the QF_LIA and QF_LRA figures are there because master had a longer timeout.

**Comment by blishko** [comment]
OK!

**Comment by aehyvari** [comment]
Closing this, there's a new PR coming.

**Pull request closed without merging**
