### PR TITLE
Changelog update

### PR DESCRIPTION
**Pull request by blishko**
Updates the changelog with the recent changes visible to the user.

### CODE REVIEW

**Comment by aehyvari** [comment]
We should add a mention on @MicTarHal's performance improvements on FastRationals.  Were there other big performance improvement recently?

**Comment by blishko** [comment]
Added entries related to performance improvements.

**Comment by aehyvari** [comment]
What if we put performance improvements as a first item so that it's more visible?  We don't have anything so far that would classify as a new feature, but once we have that, it'd be good to put that in a prominent place as well.

**Review by aehyvari — APPROVED** [review]
Good!

**Pull request merged**
