### PR TITLE
Fixing the handling of equality with more than 2 arguments

### PR DESCRIPTION
**Pull request by blishko**
Fix for issue #137

### CODE REVIEW

**Comment by rainoftime** [comment]
Is there any plan for extending inequality to support more than 2 arguments? Thanks!

**Comment by blishko** [comment]
> Is there any plan for extending inequality to support more than 2 arguments? Thanks!

Do you mean `distinct` with multiple arguments? In which context?
It should be working in QF_UF,  but I noticed some weird behaviour in QF_LRA if more than 2 arguments are used. Is that what you mean? Can you create an issue a give a more detailed description there?

**Comment by rainoftime** [comment]
Including distinct and >, >=, etc
e.g.,
~~~~
(assert (>= x y z)
~~~~

**Comment by andrewvaughanj** [comment]
@rainoftime I'm curious, do you need this for something you're building, or is this more to enable "better" bug finding?

I'm trying to understand if this is a feature request for a real-world use-case of OpenSMT vs. a "it would be nice if OpenSMT supported $n$-ary operators".

**Comment by rainoftime** [comment]
Neither. This is not a "feature request".
I am just curious (since some other solvers support the feature for both equality and inequality, and this PR extends the equality operation)

**Comment by blishko** [comment]
I have consulted the SMT-LIB standard and these operators are defined as chainable in theories of reals and integers, so it should be supported, if only to be standard-compliant.
I will create an issue for this.

**Pull request merged**
