### PR TITLE
Minor version bump

### PR DESCRIPTION
**Pull request by blishko**
The accumulated changes since last release demand a bump in minor version instead of only the patch version for the next release.

### CODE REVIEW

**Comment by Tomaqa** [comment]
The PR is not into master :]

**Comment by Tomaqa** [comment]
So you do not need a review, but I agree. Not sure though if merging to the branch will again require review of that branch.

**Comment by blishko** [comment]
With that, I express the dependency, so that this should be merged later than the other PR. When the other is merged, this is automatically rebased to target master.
And it does require a review :)

**Review by Tomaqa — APPROVED** [review]
OK it changed to master automatically :] here you go

**Pull request merged**
