### PR TITLE
Vivify regularly

### PR DESCRIPTION
**Pull request by msooseth**
Regularly vivify learnt clauses. This follows: https://www.ijcai.org/Proceedings/2017/0098.pdf This is the paper usually referred to by Armin Biere (there are some... others, but they shall be banished from the face of the Earth :laughing: )

### CODE REVIEW

**Comment by msooseth** [comment]
From the paper: ```e evaluated our approach on five of the best perform-
ing CDCL SAT solvers: Glucose [Audemard and Simon,
2009], COMiniSatPS [Oh, 2016], MapleCOMSPS [Liang et
al., 2016c], MapleCOMSPS LRB [Liang et al., 2016b] and
TC Glucose [Moon and Mary, 2016]. The experimental re-
sults show that the proposed approach allows them to solve a
remarkable number of additional instances coming from the
hard combinatorial and application categories of the 2014 and
2016 SAT competitions```

Note that this is actually really true, I'm getting way more instances solved with vivification in CryptoMiniSat. In fact, Armin used to consider vivification the first inprocessing technique adopted by SAT solvers, before kissat destroyed all other SAT solvers.

**Comment by msooseth** [comment]
Note, I'm not doing line 8 on Algorithm 2 in that paper -- analysis can be tricky with theory clauses: reasons may need to be computed. But it could be done, and it may be slightly (but only slightly) more effective, if (and likely only if) the theory reasons are cheap to compute.

**Comment by blishko** [comment]
Unlike the other changes in the SAT solver, which were very helpful, vivification does not seem to positive impact for OpenSMT on SMT-LIB benchmarks.

**Comment by blishko** [comment]
OK, I agree we should definitely revisit this, but I also don't have time at the moment.
Thanks for the all the suggested changes and pointers to the relevant papers!

**Pull request closed without merging**
