### PR TITLE
Ownership of LRAModel moved to Simplex

### PR DESCRIPTION
**Pull request by aehyvari**
A bit of refactoring.  Have a look and let me know what you think!

### CODE REVIEW

**Comment by aehyvari** [comment]
For now it looks like the Yices-style Bland adjustment makes the results worse.  I didn't expect this.
[osmt2-LRA-2019-09-18_vs_2019-10-15.pdf](https://github.com/usi-verification-and-security/opensmt/files/3732958/osmt2-LRA-2019-09-18_vs_2019-10-15.pdf)

**Comment by blishko** [comment]
I agree with disabling the Yices rule for now.
I would finish this pull request with that rule disabled and investigate further.

**Comment by aehyvari** [comment]
Yes, I committed a version without that, and run the LRA instances on the
cluster with the reverted version to make sure it's not some other
weirdness.  Once that's done and all looks normal, I think we're good to
merge.

**Comment by aehyvari** [comment]
The performance in the pull request is consistent with the current master.  I'll try to figure out why rebasing doesn't work and the do the thing.

[osmt2-LRA-2019-09-18_vs_2019-10-16.pdf](https://github.com/usi-verification-and-security/opensmt/files/3735018/osmt2-LRA-2019-09-18_vs_2019-10-16.pdf)

**Comment by blishko** [comment]
Looking at the graph, it almost looks like you started the branch on top of some stash. It has some non-linear structure for reason I do not understand. 
Probably just do the merge.

**Pull request merged**
